---
- name: Ensure Pip 3 is installed.
  package:
    name: "{{ pip_package }}"
    state: present

- name: Ensure Pip 2 is installed.
  package:
    name: python-pip
    state: present

- name: Ensure pip_3_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "pip3"
  with_items: "{{ pip_3_packages }}"

- name: Ensure pip_2_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "pip"
  with_items: "{{ pip_2_packages }}"
